// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class CreateOutline {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void CreateOutline() {
    driver.get("http://gc21131138.imwork.net:20430/test-maker/web/admin/index.action#");

    driver.findElement(By.id("username")).sendKeys("XieDongfang");
    driver.findElement(By.id("password")).sendKeys("12306abc");
    driver.findElement(By.id("login-button")).click();
    System.out.println("click login-button");

    driver.manage().timeouts().implicitlyWait(1000L, TimeUnit.SECONDS);
    driver.findElement(By.linkText("大纲管理")).click();

    driver.findElement(By.id("edit-syllabus-form-btn")).click();
    driver.findElement(By.id("syllabus-level")).click();
    driver.findElement(By.id("syllabus-level")).sendKeys("Ad ApAAAA");
    driver.findElement(By.id("syllabus-version")).click();
    driver.findElement(By.id("syllabus-version")).sendKeys("v1.0");
    driver.findElement(By.id("update-syllabus-btn")).click();
    driver.findElement(By.id("73407e36-e99c-4a43-856c-badb0f4cdd23")).click();
    driver.findElement(By.id("4749e5f8-94be-431d-8a58-cc613c55c737")).click();
  }
}
