package outline;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class AddChapter {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "driver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void AddChapterTest() throws InterruptedException {
    driver.get("http://gc21131138.imwork.net:20430/test-maker/web/admin/index.action#");
    driver.findElement(By.id("username")).sendKeys("XieDongfang");
    driver.findElement(By.id("password")).sendKeys("12306abc");
    driver.findElement(By.id("login-button")).click();
    System.out.println("login as XieDongfang");

    driver.manage().timeouts().implicitlyWait(1000L, TimeUnit.SECONDS);
    driver.findElement(By.linkText("大纲管理")).click();
    System.out.println("进入大纲管理页面");

    driver.findElement(By.id("chapter-tab-title")).click();
    System.out.println("进入章节页面");

    driver.findElement(By.id("create-chapter-btn")).click();
    driver.findElement(By.xpath("//*[@id=\"create-chapter-form\"]/div[1]/div/span/span[1]/span/span[2]")).click();
    driver.findElement(By.xpath("//span/input")).sendKeys("Ad 11");
    Thread.sleep(1000L);
    JavascriptExecutor js = (JavascriptExecutor) driver;
    js.executeScript("document.querySelector('ul.select2-results__options').children[0].click()");
    driver.findElement(By.id("chapter-number")).sendKeys("1");
    driver.findElement(By.id("chapter-name")).sendKeys("第一章");
    driver.findElement(By.id("submit-chapter-btn")).click();
    System.out.println("创建新的章节");

    Thread.sleep(10000L);
    WebElement successEle = driver.findElement(By.cssSelector("div.modal-dialog div.bootstrap-dialog-message"));
    System.out.println(successEle.getText());
    assertEquals(successEle.getText(), "操作成功！");
    System.out.println("创建新章节成功！");
  }
}
