package outline;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class StopUsingOutline {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "driver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void StopUsingOutlineTest() throws InterruptedException {
    driver.get("http://gc21131138.imwork.net:20430/test-maker/web/admin/index.action#");
    driver.findElement(By.id("username")).sendKeys("XieDongfang");
    driver.findElement(By.id("password")).sendKeys("12306abc");
    driver.findElement(By.id("login-button")).click();
    System.out.println("login as XieDongfang");

    driver.manage().timeouts().implicitlyWait(100L, TimeUnit.SECONDS);
    driver.findElement(By.linkText("大纲管理")).click();
    System.out.println("进入大纲管理页面");

    driver.findElement(By.id("syllabus-keyword")).sendKeys("Ad 11");
    driver.findElement(By.cssSelector("#search-syllabus-btn > .glyphicon")).click();
    System.out.println("查找大纲");

    driver.findElement(By.cssSelector(".item-row:nth-child(1) .edit-item > .glyphicon")).click();
    driver.findElement(By.cssSelector(".bootstrap-switch-label")).click();
    driver.findElement(By.id("update-syllabus-btn")).click();
    driver.findElement(By.xpath("//div[3]/div/div/button[2]")).click();
    System.out.println("停用大纲");

    Thread.sleep(10000L);
    WebElement successEle = driver.findElement(By.cssSelector("div.modal-dialog div.bootstrap-dialog-message"));
    System.out.println(successEle.getText());
    assertEquals(successEle.getText(), "操作成功！");
    System.out.println("停用成功！");
  }
}
